name: datares1-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7 
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - tqdm
  - tensorflow
  - keras
  - jupyter
  - nb_conda_kernels
  - textdistance
  - networkx
  - editdistance
